"""Bcfg2 errors for reporting why a process exited"""

# Generic errors
NO_ERROR = 0
SYNTAX_ERROR = 1
SIGNAL_INTERRUPT = 2
FATAL_ERROR = 3

# Client errors
NO_PROFILE = 4

PROBE_EXECUTE_FAILURE = 5
PROBE_DOWNLOAD_FAILURE = 6
PROBE_UPLOAD_FAILURE = 7

DECISION_FAILURE = 8
CONFIGURATION_DOWNLOAD_FAILURE = 9
STATISTICS_UPLOAD_FAILURE = 10

